// import './globals.css'
// import { Inter } from 'next/font/google'

// const inter = Inter({ subsets: ['latin'] })

// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

// export default function RootLayout({
//   children,
// }: {
//   children: React.ReactNode
// }) {
//   return (
//     <html lang="en">
//       <body className={inter.className}>{children}</body>
//     </html>
//   )
// }

// app/layout.tsx

import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Navbar from "../components/ui/Navbar";
import Footer from "../components/ui/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Sanity Next.js Portfolio Site",
  description: "A personal portfolio site built with Sanity and Next.js",
  openGraph: {
    images: "add-your-open-graph-image-url-here",
  },
};

// This function is absolutely working.

// export default function RootLayout({children}: {children: React.ReactNode}) {

//   const isLoggedin = true
//   return (

//           <html lang="en">
//           <body className={`${inter.className} bg-zinc-900 text-white`}>
//             <Navbar />
//             {children}
//             <Footer />
//           </body>
//         </html>
//   )
// }

export default function RootLayout({ children }: { children: React.ReactNode }) {
  const isLoggedin = true;
  return isLoggedin ? (
    <html lang="en">
      <body className={`${inter.className} bg-zinc-900 text-white`}>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  ) : (
    <html lang="en">
      <body className={`${inter.className} bg-white text-black`}>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
